{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jmc",
    "module": "jmc-utils",
    "version": "3.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jmc-utils-3.9.0.jar",
          "url": "jmc-utils-3.9.0.jar",
          "size": 158597,
          "sha512": "3471bf5693ba3523cffaa28441a99e683cc87b360e63aefc146b5fa0defc14fcd1b265a2ea3467657ff88f9660d5431666248bbf8f589ab84d7903df7dbe9d14",
          "sha256": "18367d2d97754ad32eb119cdc5940ea745c89aa63addd96ea8f174de2d3eeb81",
          "sha1": "c67a2c26aed6e157a25b2d0812c38d3c87052124",
          "md5": "c3ac11d4018b07219d5c04562452eeed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "jmc-utils-3.9.0.jar",
          "url": "jmc-utils-3.9.0.jar",
          "size": 158597,
          "sha512": "3471bf5693ba3523cffaa28441a99e683cc87b360e63aefc146b5fa0defc14fcd1b265a2ea3467657ff88f9660d5431666248bbf8f589ab84d7903df7dbe9d14",
          "sha256": "18367d2d97754ad32eb119cdc5940ea745c89aa63addd96ea8f174de2d3eeb81",
          "sha1": "c67a2c26aed6e157a25b2d0812c38d3c87052124",
          "md5": "c3ac11d4018b07219d5c04562452eeed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jmc-utils-3.9.0-sources.jar",
          "url": "jmc-utils-3.9.0-sources.jar",
          "size": 73201,
          "sha512": "2838627ea034927c074a190b18d0f37e91706dccbfc2fe1c2d54e6facc8d2e90e1dae7e156b3f31395371563c1d369acf2f0ddabc80906b93780edfca2799d67",
          "sha256": "28a0dc4ed728caaf3d7d5b17519688b8b2e0d487470a2a5253e8b55a0fc2eb9b",
          "sha1": "18ae5d23de219dea7ae93e12a531d604ee68f408",
          "md5": "f11c0cb8419a0c641c7820b5886533a5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jmc-utils-3.9.0-javadoc.jar",
          "url": "jmc-utils-3.9.0-javadoc.jar",
          "size": 427979,
          "sha512": "46fb57fb49823b729cd5d34f350ea27cce7a6828ea744b4c43e65d94d4225b525167fda19739192e2efcb5932145c36d6fded0252553285b0f5daff417d7c740",
          "sha256": "48d977211c29cced9fdbd02fa8c9a5aef33fb8fbd08eae3863f31d7e7f1cc673",
          "sha1": "404e2ffd815dc8082bc5ab96d51138fe543a05e5",
          "md5": "690d7fd6bedb544bdc819791f323d574"
        }
      ]
    }
  ]
}
