{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jmc",
    "module": "jmc-utils",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jmc-utils-3.0.0.jar",
          "url": "jmc-utils-3.0.0.jar",
          "size": 149210,
          "sha512": "aafbb0ac8999042815edeff72c20315d1c1610676efbc715825bfc17c21a05b418e0297d5303a548fd8125bd6f2e30d6c5c97b41d14bad1ab2d7145071ac2184",
          "sha256": "0729f451b1ef8a194a2d8c9817ab770c20bf9cf83e306683232c9ff9a0257973",
          "sha1": "77ed9e9c7a6aecf3bfab57e8039e711e5b47a3b4",
          "md5": "5e1681bdf2de0bad7591c7d318603a80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        }
      ],
      "files": [
        {
          "name": "jmc-utils-3.0.0.jar",
          "url": "jmc-utils-3.0.0.jar",
          "size": 149210,
          "sha512": "aafbb0ac8999042815edeff72c20315d1c1610676efbc715825bfc17c21a05b418e0297d5303a548fd8125bd6f2e30d6c5c97b41d14bad1ab2d7145071ac2184",
          "sha256": "0729f451b1ef8a194a2d8c9817ab770c20bf9cf83e306683232c9ff9a0257973",
          "sha1": "77ed9e9c7a6aecf3bfab57e8039e711e5b47a3b4",
          "md5": "5e1681bdf2de0bad7591c7d318603a80"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jmc-utils-3.0.0-sources.jar",
          "url": "jmc-utils-3.0.0-sources.jar",
          "size": 53165,
          "sha512": "7cfd8be35864db681dc31fb9444d5fa15743c5035bedcde65dd030c3adb4da130590e829a61a5b735433223d388f1dc19f79e005d67df152e15242168113bf76",
          "sha256": "6b2a9e42a7acaa3fb134eb809f9fecccf1c636c21d22c1ded623c8724a2f3377",
          "sha1": "768b4e2c177fd7ce95bea7d34e11477591bcd98c",
          "md5": "baa13f8b9f1adbff2d6b5ee8d9236e43"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jmc-utils-3.0.0-javadoc.jar",
          "url": "jmc-utils-3.0.0-javadoc.jar",
          "size": 349506,
          "sha512": "1b8e15e07cabe09e6d27e8dc1579b9f4a48f04f049cb3b3397109cf158d87c5d521b1fc9a86394f20bca282f1744ca0408ea8b12b49bd4c5794731305a8acf2f",
          "sha256": "75669a1961b270444e8226c928e61fcfced9f8836713dad99a1dbc174117c464",
          "sha1": "8d9904ef79bdcc13153f7a8b0394e564d7d9c803",
          "md5": "ea2a3bbba4e6b4a33fdd5caf83c58ffd"
        }
      ]
    }
  ]
}
