{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jmc",
    "module": "jmc-utils",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jmc-utils-3.1.0.jar",
          "url": "jmc-utils-3.1.0.jar",
          "size": 149540,
          "sha512": "3df70ca88412b384e7e92f75a3aacf3133a1401c59b8fc0586784cb980f8451fc648d8ff1e64d7e3cd61faf705ec228360ab0301fc08090db366e34c9d310ee8",
          "sha256": "60c798264f4889540cb420ad156dfcf2e98c5e12fd87eb9c90514a9b306b8540",
          "sha1": "74b7233b93be123fb7a81d7276557be4bb215e94",
          "md5": "551a3dbb11b108ddb5cac3d28dbb6e84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjrt",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        }
      ],
      "files": [
        {
          "name": "jmc-utils-3.1.0.jar",
          "url": "jmc-utils-3.1.0.jar",
          "size": 149540,
          "sha512": "3df70ca88412b384e7e92f75a3aacf3133a1401c59b8fc0586784cb980f8451fc648d8ff1e64d7e3cd61faf705ec228360ab0301fc08090db366e34c9d310ee8",
          "sha256": "60c798264f4889540cb420ad156dfcf2e98c5e12fd87eb9c90514a9b306b8540",
          "sha1": "74b7233b93be123fb7a81d7276557be4bb215e94",
          "md5": "551a3dbb11b108ddb5cac3d28dbb6e84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jmc-utils-3.1.0-sources.jar",
          "url": "jmc-utils-3.1.0-sources.jar",
          "size": 62251,
          "sha512": "cf3c8f1868b94f710d510f6430b6edfc890b27d2d169722bf8b82b68cf42d1ae402ca7da1669392e683e9e6963b85b7055727e501b3a5de6717ed739a93411d3",
          "sha256": "988a5a47f76189e76de060b899aa1575cc68b2bff83a4239946caec97e1a2b7c",
          "sha1": "46fe843c640b644939760c32aa12939075dd6f46",
          "md5": "98e01dbade416f9d2971f4287af0a02c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jmc-utils-3.1.0-javadoc.jar",
          "url": "jmc-utils-3.1.0-javadoc.jar",
          "size": 359383,
          "sha512": "7accb25ad8e570d0fb8bebaa84fc20940212dcf458cece013aea06055d0b51fb00baecab53954ad324cf018fdbf331d7f4ef747fbbab07f80a99e2ca8654dc5a",
          "sha256": "4a7978724f266f3f048ef66f2dc96b2b10481de729aad45297fdfeca707b1129",
          "sha1": "806462807ffc51877708365ce2796b0fb3fbe653",
          "md5": "ba72253abc5696fd00bc27ee6298e2f8"
        }
      ]
    }
  ]
}
