{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jmc",
    "module": "jmc-utils",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jmc-utils-3.3.0.jar",
          "url": "jmc-utils-3.3.0.jar",
          "size": 153538,
          "sha512": "fe565b8e85cabfe03de73b2003c3b8b7016ba931145e4c8109ddffee48c0e17f6c667540b0c186e5b5fa30eb7087a169f28c7dbfc9d9fb1d0cc60f2ef106aea1",
          "sha256": "fa0ed268bf91180a615424ea10d2cd0f2fcc77bff69c3edfb3be703d8a4763df",
          "sha1": "aca83a36a6dba7b4075fd08e0dace66d19c96aea",
          "md5": "f9f524122e1d998527ae00e49a360b58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjrt",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        }
      ],
      "files": [
        {
          "name": "jmc-utils-3.3.0.jar",
          "url": "jmc-utils-3.3.0.jar",
          "size": 153538,
          "sha512": "fe565b8e85cabfe03de73b2003c3b8b7016ba931145e4c8109ddffee48c0e17f6c667540b0c186e5b5fa30eb7087a169f28c7dbfc9d9fb1d0cc60f2ef106aea1",
          "sha256": "fa0ed268bf91180a615424ea10d2cd0f2fcc77bff69c3edfb3be703d8a4763df",
          "sha1": "aca83a36a6dba7b4075fd08e0dace66d19c96aea",
          "md5": "f9f524122e1d998527ae00e49a360b58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jmc-utils-3.3.0-sources.jar",
          "url": "jmc-utils-3.3.0-sources.jar",
          "size": 64343,
          "sha512": "0476f57e0f36bd2c276c0ae26761824d055b94da15dbce3ad7a6be01eaf669ebf004b2d924153564abfea821e80e7f2626d73364d58bfbccd59a2cc458a70bb5",
          "sha256": "e18b0faef59ee093f6a92169e5d14e47896801b70fe663397d0e5ea8a1037bc2",
          "sha1": "02e5d5b7c5c426a55f00b418a9b51e7b354432c8",
          "md5": "a4d77358a568e00271ecb181340ce1ab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jmc-utils-3.3.0-javadoc.jar",
          "url": "jmc-utils-3.3.0-javadoc.jar",
          "size": 366086,
          "sha512": "1aac7369a000eb105cdbb1d0c2156ca5ccb30c8f415855fa4625658a143aa56d978529dfbe07e08d2290cbd55aa1903c255e5efe30743a939f47d20e6d89ada0",
          "sha256": "16e90ace029f78126f8edcfbcfd556791e55589d369bfc382af078cf0c6219c2",
          "sha1": "0be3114d28307f0167cd7e9fadbbdd6c3a0361e6",
          "md5": "990ce0ba56c76e43a849b1e775defe5b"
        }
      ]
    }
  ]
}
